image:
  file: .gitpod.Dockerfile
# https://www.gitpod.io/docs/config-start-tasks/#start-tasks
tasks:
  - prebuild: echo "PREBUILD START" && echo "PREBUILD RUN" && echo "PREBUILD STOP"
  - before: echo "BEFORE START" && echo "BEFORE RUN" && echo "BEFORE STOP"
  - init: echo "INIT START" && echo "INIT RUN" && echo "INIT STOP"
  - command: echo "COMMAND START" && echo "COMMAND RUN" && echo "COMMAND STOP"
  - command: echo "COMMAND START" && ./scripts/linux/gitConfig.sh && git stash push && git flow init -d && ( git stash pop || true ) && echo "COMMAND STOP" && exit 0
vscode:
  extensions:
    - nimsaem.nimvscode
    - redhat.vscode-yaml
