# Check here https://config.travis-ci.com/explore
# Format here https://jsonformatter.org/yaml-formatter
os: linux
dist: xenial
language: c
compiler: gcc
branches:
  only:
    - master
    - develop
    - '/^release\/.*$/'
    - '/^hotfix\/.*$/'
cache:
  directories:
    - "$HOME/.choosenim"
env:
  global:
    - CACHE_NAME=ChooseNim
    - NIM_VERBOSITY=0
  matrix:
    - "NIM_TARGET_OS=linux NIM_TARGET_CPU=amd64 USE_GCC=9 NIM_TAG_SELECTOR=stable NIM_GC=refc"
    - "NIM_TARGET_OS=linux NIM_TARGET_CPU=amd64 USE_GCC=9 NIM_TAG_SELECTOR=stable NIM_GC=arc"
    - "NIM_TARGET_OS=linux NIM_TARGET_CPU=amd64 USE_GCC=9 NIM_TAG_SELECTOR=devel NIM_GC=refc"
    - "NIM_TARGET_OS=linux NIM_TARGET_CPU=amd64 USE_GCC=9 NIM_TAG_SELECTOR=devel NIM_GC=arc"
    - "NIM_TARGET_OS=linux NIM_TARGET_CPU=i386 USE_GCC=9 NIM_TAG_SELECTOR=stable NIM_GC=refc"
    - "NIM_TARGET_OS=linux NIM_TARGET_CPU=i386 USE_GCC=9 NIM_TAG_SELECTOR=stable NIM_GC=arc"
    - "NIM_TARGET_OS=linux NIM_TARGET_CPU=i386 USE_GCC=9 NIM_TAG_SELECTOR=devel NIM_GC=refc"
    - "NIM_TARGET_OS=linux NIM_TARGET_CPU=i386 USE_GCC=9 NIM_TAG_SELECTOR=devel NIM_GC=arc"
    - "NIM_TARGET_OS=windows NIM_TARGET_CPU=amd64 USE_GCC=9 NIM_TAG_SELECTOR=stable NIM_GC=refc"
    - "NIM_TARGET_OS=windows NIM_TARGET_CPU=amd64 USE_GCC=9 NIM_TAG_SELECTOR=stable NIM_GC=arc"
    - "NIM_TARGET_OS=windows NIM_TARGET_CPU=amd64 USE_GCC=9 NIM_TAG_SELECTOR=devel NIM_GC=refc"
    - "NIM_TARGET_OS=windows NIM_TARGET_CPU=amd64 USE_GCC=9 NIM_TAG_SELECTOR=devel NIM_GC=arc"
    - "NIM_TARGET_OS=windows NIM_TARGET_CPU=i386 USE_GCC=9 NIM_TAG_SELECTOR=stable NIM_GC=refc"
    - "NIM_TARGET_OS=windows NIM_TARGET_CPU=i386 USE_GCC=9 NIM_TAG_SELECTOR=stable NIM_GC=arc"
    - "NIM_TARGET_OS=windows NIM_TARGET_CPU=i386 USE_GCC=9 NIM_TAG_SELECTOR=devel NIM_GC=refc"
    - "NIM_TARGET_OS=windows NIM_TARGET_CPU=i386 USE_GCC=9 NIM_TAG_SELECTOR=devel NIM_GC=arc"

script:
  - ./scripts/linux/travis.sh
