
os: linux
dist: trusty
language: c
compiler: gcc
sudo: required

branches:
  only:
    - master
    - develop
    - /^release\/.*$/
    - /^hotfix\/.*$/
env:
  global:
    - NIM_VERBOSITY=0
  matrix:
    - NIM_TARGET_OS=linux NIM_TARGET_CPU=amd64 USE_GCC=4.8
    - NIM_TARGET_OS=linux NIM_TARGET_CPU=amd64 USE_GCC=5
    - NIM_TARGET_OS=linux NIM_TARGET_CPU=amd64 USE_GCC=6
    - NIM_TARGET_OS=linux NIM_TARGET_CPU=amd64 USE_GCC=7
    - NIM_TARGET_OS=linux NIM_TARGET_CPU=amd64 USE_GCC=8
    - NIM_TARGET_OS=linux NIM_TARGET_CPU=i386 USE_GCC=4.8
    - NIM_TARGET_OS=linux NIM_TARGET_CPU=i386 USE_GCC=5
    - NIM_TARGET_OS=linux NIM_TARGET_CPU=i386 USE_GCC=6
    - NIM_TARGET_OS=linux NIM_TARGET_CPU=i386 USE_GCC=7
    - NIM_TARGET_OS=linux NIM_TARGET_CPU=i386 USE_GCC=8
    - NIM_TARGET_OS=windows NIM_TARGET_CPU=amd64 USE_GCC=4.8
    - NIM_TARGET_OS=windows NIM_TARGET_CPU=amd64 USE_GCC=5
    - NIM_TARGET_OS=windows NIM_TARGET_CPU=amd64 USE_GCC=6
    - NIM_TARGET_OS=windows NIM_TARGET_CPU=amd64 USE_GCC=7
    - NIM_TARGET_OS=windows NIM_TARGET_CPU=amd64 USE_GCC=8
    - NIM_TARGET_OS=windows NIM_TARGET_CPU=i386 USE_GCC=4.8
    - NIM_TARGET_OS=windows NIM_TARGET_CPU=i386 USE_GCC=5
    - NIM_TARGET_OS=windows NIM_TARGET_CPU=i386 USE_GCC=6
    - NIM_TARGET_OS=windows NIM_TARGET_CPU=i386 USE_GCC=7
    - NIM_TARGET_OS=windows NIM_TARGET_CPU=i386 USE_GCC=8
script:
  - ./scripts/linux/travis.sh
