
os: linux
dist: trusty
language: c
compiler: gcc
sudo: required

env:
  global:
    - nimVerbosity=1
  matrix:
    - nim_branch=master nimTargetCPU=amd64
    - nim_branch=master nimTargetCPU=i386
    - nim_branch=devel nimTargetCPU=amd64
    - nim_branch=devel nimTargetCPU=i386
    - nim_branch=master nimTargetCPU=amd64 useGCC=4.9
    - nim_branch=master nimTargetCPU=i386 useGCC=4.9
    - nim_branch=devel nimTargetCPU=amd64 useGCC=4.9
    - nim_branch=devel nimTargetCPU=i386 useGCC=4.9
    - nim_branch=master nimTargetCPU=amd64 useGCC=5
    - nim_branch=master nimTargetCPU=i386 useGCC=5
    - nim_branch=devel nimTargetCPU=amd64 useGCC=5
    - nim_branch=devel nimTargetCPU=i386 useGCC=5
    - nim_branch=master nimTargetCPU=amd64 useGCC=6
    - nim_branch=master nimTargetCPU=i386 useGCC=6
    - nim_branch=devel nimTargetCPU=amd64 useGCC=6
    - nim_branch=devel nimTargetCPU=i386 useGCC=6
    - nim_branch=master nimTargetCPU=amd64 useGCC=7
    - nim_branch=master nimTargetCPU=i386 useGCC=7
    - nim_branch=devel nimTargetCPU=amd64 useGCC=7
    - nim_branch=devel nimTargetCPU=i386 useGCC=7

matrix:
  allow_failures:
    env:
      - nim_branch=devel nimTargetCPU=amd64
      - nim_branch=devel nimTargetCPU=i386
      - nim_branch=devel nimTargetCPU=amd64 useGCC=4.9
      - nim_branch=devel nimTargetCPU=i386 useGCC=4.9
      - nim_branch=devel nimTargetCPU=amd64 useGCC=5
      - nim_branch=devel nimTargetCPU=i386 useGCC=5
      - nim_branch=devel nimTargetCPU=amd64 useGCC=6
      - nim_branch=devel nimTargetCPU=i386 useGCC=6
      - nim_branch=devel nimTargetCPU=amd64 useGCC=7
      - nim_branch=devel nimTargetCPU=i386 useGCC=7
  fast_finish: true

script:
  - ./scripts/linux/travis.sh

cache:
  directories:
    - toCache
