
os: linux
dist: trusty
language: c
compiler: gcc
sudo: required

env:
  global:
    - nimVerbosity=3
  matrix:
    - useGCC=4.8 nim_branch=master nimTargetOS=linux nimTargetCPU=amd64
    - useGCC=4.8 nim_branch=master nimTargetOS=linux nimTargetCPU=i386
    # - useGCC=4.8 nim_branch=master nimTargetOS=windows nimTargetCPU=amd64
    # - useGCC=4.8 nim_branch=master nimTargetOS=windows nimTargetCPU=i386
    # - useGCC=4.8 nim_branch=devel nimTargetOS=linux nimTargetCPU=amd64
    # - useGCC=4.8 nim_branch=devel nimTargetOS=linux nimTargetCPU=i386
    # - useGCC=4.8 nim_branch=devel nimTargetOS=windows nimTargetCPU=amd64
    # - useGCC=4.8 nim_branch=devel nimTargetOS=windows nimTargetCPU=i386
    # - useGCC=4.9 nim_branch=master nimTargetOS=linux nimTargetCPU=amd64
    # - useGCC=4.9 nim_branch=master nimTargetOS=linux nimTargetCPU=i386
    # - useGCC=4.9 nim_branch=master nimTargetOS=windows nimTargetCPU=amd64
    # - useGCC=4.9 nim_branch=master nimTargetOS=windows nimTargetCPU=i386
    # - useGCC=4.9 nim_branch=devel nimTargetOS=linux nimTargetCPU=amd64
    # - useGCC=4.9 nim_branch=devel nimTargetOS=linux nimTargetCPU=i386
    # - useGCC=4.9 nim_branch=devel nimTargetOS=windows nimTargetCPU=amd64
    # - useGCC=4.9 nim_branch=devel nimTargetOS=windows nimTargetCPU=i386
    # - useGCC=5 nim_branch=master nimTargetOS=linux nimTargetCPU=amd64
    # - useGCC=5 nim_branch=master nimTargetOS=linux nimTargetCPU=i386
    # - useGCC=5 nim_branch=master nimTargetOS=windows nimTargetCPU=amd64
    # - useGCC=5 nim_branch=master nimTargetOS=windows nimTargetCPU=i386
    # - useGCC=5 nim_branch=devel nimTargetOS=linux nimTargetCPU=amd64
    # - useGCC=5 nim_branch=devel nimTargetOS=linux nimTargetCPU=i386
    # - useGCC=5 nim_branch=devel nimTargetOS=windows nimTargetCPU=amd64
    # - useGCC=5 nim_branch=devel nimTargetOS=windows nimTargetCPU=i386
    # - useGCC=6 nim_branch=master nimTargetOS=linux nimTargetCPU=amd64
    # - useGCC=6 nim_branch=master nimTargetOS=linux nimTargetCPU=i386
    # - useGCC=6 nim_branch=master nimTargetOS=windows nimTargetCPU=amd64
    # - useGCC=6 nim_branch=master nimTargetOS=windows nimTargetCPU=i386
    # - useGCC=6 nim_branch=devel nimTargetOS=linux nimTargetCPU=amd64
    # - useGCC=6 nim_branch=devel nimTargetOS=linux nimTargetCPU=i386
    # - useGCC=6 nim_branch=devel nimTargetOS=windows nimTargetCPU=amd64
    # - useGCC=6 nim_branch=devel nimTargetOS=windows nimTargetCPU=i386
    # - useGCC=7 nim_branch=master nimTargetOS=linux nimTargetCPU=amd64
    # - useGCC=7 nim_branch=master nimTargetOS=linux nimTargetCPU=i386
    # - useGCC=7 nim_branch=master nimTargetOS=windows nimTargetCPU=amd64
    # - useGCC=7 nim_branch=master nimTargetOS=windows nimTargetCPU=i386
    # - useGCC=7 nim_branch=devel nimTargetOS=linux nimTargetCPU=amd64
    # - useGCC=7 nim_branch=devel nimTargetOS=linux nimTargetCPU=i386
    # - useGCC=7 nim_branch=devel nimTargetOS=windows nimTargetCPU=amd64
    # - useGCC=7 nim_branch=devel nimTargetOS=windows nimTargetCPU=i386

matrix:
  allow_failures:
    env:
      - useGCC=4.8 nim_branch=devel nimTargetOS=linux nimTargetCPU=amd64
      - useGCC=4.8 nim_branch=devel nimTargetOS=linux nimTargetCPU=i386
      - useGCC=4.8 nim_branch=devel nimTargetOS=windows nimTargetCPU=amd64
      - useGCC=4.8 nim_branch=devel nimTargetOS=windows nimTargetCPU=i386
      - useGCC=4.9 nim_branch=devel nimTargetOS=linux nimTargetCPU=amd64
      - useGCC=4.9 nim_branch=devel nimTargetOS=linux nimTargetCPU=i386
      - useGCC=4.9 nim_branch=devel nimTargetOS=windows nimTargetCPU=amd64
      - useGCC=4.9 nim_branch=devel nimTargetOS=windows nimTargetCPU=i386
      - useGCC=5 nim_branch=devel nimTargetOS=linux nimTargetCPU=amd64
      - useGCC=5 nim_branch=devel nimTargetOS=linux nimTargetCPU=i386
      - useGCC=5 nim_branch=devel nimTargetOS=windows nimTargetCPU=amd64
      - useGCC=5 nim_branch=devel nimTargetOS=windows nimTargetCPU=i386
      - useGCC=6 nim_branch=devel nimTargetOS=linux nimTargetCPU=amd64
      - useGCC=6 nim_branch=devel nimTargetOS=linux nimTargetCPU=i386
      - useGCC=6 nim_branch=devel nimTargetOS=windows nimTargetCPU=amd64
      - useGCC=6 nim_branch=devel nimTargetOS=windows nimTargetCPU=i386
      - useGCC=7 nim_branch=devel nimTargetOS=linux nimTargetCPU=amd64
      - useGCC=7 nim_branch=devel nimTargetOS=linux nimTargetCPU=i386
      - useGCC=7 nim_branch=devel nimTargetOS=windows nimTargetCPU=amd64
      - useGCC=7 nim_branch=devel nimTargetOS=windows nimTargetCPU=i386
  fast_finish: true

script:
  - ./scripts/linux/travis.sh

cache:
  directories:
    - toCache
