build_cloud: ubuntu
build_script:
  - sh: ./scripts/linux/travis.sh
environment:
  matrix:
    - NIM_GC: refc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 6
    - NIM_GC: arc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 6
    - NIM_GC: orc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 6
    - NIM_GC: refc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: windows
      USE_GCC: 6
    - NIM_GC: arc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: windows
      USE_GCC: 6
    - NIM_GC: orc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: windows
      USE_GCC: 6
    - NIM_GC: refc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 6
    - NIM_GC: arc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 6
    - NIM_GC: orc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 6
    - NIM_GC: refc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: windows
      USE_GCC: 6
    - NIM_GC: arc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: windows
      USE_GCC: 6
    - NIM_GC: orc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: windows
      USE_GCC: 6
    - NIM_GC: refc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 7
    - NIM_GC: arc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 7
    - NIM_GC: orc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 7
    - NIM_GC: refc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: windows
      USE_GCC: 7
    - NIM_GC: arc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: windows
      USE_GCC: 7
    - NIM_GC: orc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: windows
      USE_GCC: 7
    - NIM_GC: refc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 7
    - NIM_GC: arc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 7
    - NIM_GC: orc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 7
    - NIM_GC: refc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: windows
      USE_GCC: 7
    - NIM_GC: arc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: windows
      USE_GCC: 7
    - NIM_GC: orc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: windows
      USE_GCC: 7
    - NIM_GC: refc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 9
    - NIM_GC: arc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 9
    - NIM_GC: orc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 9
    - NIM_GC: refc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: windows
      USE_GCC: 9
    - NIM_GC: arc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: windows
      USE_GCC: 9
    - NIM_GC: orc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: windows
      USE_GCC: 9
    - NIM_GC: refc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 9
    - NIM_GC: arc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 9
    - NIM_GC: orc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 9
    - NIM_GC: refc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: windows
      USE_GCC: 9
    - NIM_GC: arc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: windows
      USE_GCC: 9
    - NIM_GC: orc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: windows
      USE_GCC: 9
    - NIM_GC: refc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 11
    - NIM_GC: arc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 11
    - NIM_GC: orc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 11
    - NIM_GC: refc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: windows
      USE_GCC: 11
    - NIM_GC: arc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: windows
      USE_GCC: 11
    - NIM_GC: orc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: windows
      USE_GCC: 11
    - NIM_GC: refc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 11
    - NIM_GC: arc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 11
    - NIM_GC: orc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 11
    - NIM_GC: refc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: windows
      USE_GCC: 11
    - NIM_GC: arc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: windows
      USE_GCC: 11
    - NIM_GC: orc
      NIM_TAG_SELECTOR: 1.6.0
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: windows
      USE_GCC: 11
    - NIM_GC: refc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 6
    - NIM_GC: arc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 6
    - NIM_GC: orc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 6
    - NIM_GC: refc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: windows
      USE_GCC: 6
    - NIM_GC: arc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: windows
      USE_GCC: 6
    - NIM_GC: orc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: windows
      USE_GCC: 6
    - NIM_GC: refc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 6
    - NIM_GC: arc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 6
    - NIM_GC: orc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 6
    - NIM_GC: refc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: windows
      USE_GCC: 6
    - NIM_GC: arc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: windows
      USE_GCC: 6
    - NIM_GC: orc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: windows
      USE_GCC: 6
    - NIM_GC: refc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 7
    - NIM_GC: arc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 7
    - NIM_GC: orc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 7
    - NIM_GC: refc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: windows
      USE_GCC: 7
    - NIM_GC: arc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: windows
      USE_GCC: 7
    - NIM_GC: orc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: windows
      USE_GCC: 7
    - NIM_GC: refc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 7
    - NIM_GC: arc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 7
    - NIM_GC: orc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 7
    - NIM_GC: refc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: windows
      USE_GCC: 7
    - NIM_GC: arc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: windows
      USE_GCC: 7
    - NIM_GC: orc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: windows
      USE_GCC: 7
    - NIM_GC: refc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 9
    - NIM_GC: arc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 9
    - NIM_GC: orc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 9
    - NIM_GC: refc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: windows
      USE_GCC: 9
    - NIM_GC: arc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: windows
      USE_GCC: 9
    - NIM_GC: orc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: windows
      USE_GCC: 9
    - NIM_GC: refc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 9
    - NIM_GC: arc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 9
    - NIM_GC: orc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 9
    - NIM_GC: refc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: windows
      USE_GCC: 9
    - NIM_GC: arc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: windows
      USE_GCC: 9
    - NIM_GC: orc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: windows
      USE_GCC: 9
    - NIM_GC: refc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 11
    - NIM_GC: arc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 11
    - NIM_GC: orc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 11
    - NIM_GC: refc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: windows
      USE_GCC: 11
    - NIM_GC: arc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: windows
      USE_GCC: 11
    - NIM_GC: orc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: windows
      USE_GCC: 11
    - NIM_GC: refc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 11
    - NIM_GC: arc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 11
    - NIM_GC: orc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 11
    - NIM_GC: refc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: windows
      USE_GCC: 11
    - NIM_GC: arc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: windows
      USE_GCC: 11
    - NIM_GC: orc
      NIM_TAG_SELECTOR: 1.4.8
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: windows
      USE_GCC: 11
image: Ubuntu1804
version: 1.0.{build}
