# https://www.appveyor.com/docs/appveyor-yml/
version: 1.0.{build}
build_cloud: ubuntu Docker
image: ubuntu
environment:
  matrix:
  - NIM_TARGET_OS: linux
    NIM_TARGET_CPU: amd64
    USE_GCC: 9
    NIM_TAG_SELECTOR: stable
    NIM_GC: refc
  - NIM_TARGET_OS: linux
    NIM_TARGET_CPU: amd64
    USE_GCC: 9
    NIM_TAG_SELECTOR: devel
    NIM_GC: refc
  - NIM_TARGET_OS: windows
    NIM_TARGET_CPU: amd64
    USE_GCC: 9
    NIM_TAG_SELECTOR: stable
    NIM_GC: orc
build_script:
- sh: ./scripts/linux/travis.sh
