# https://www.appveyor.com/docs/appveyor-yml/
build_cloud: ubuntu Docker
build_script:
  - sh: ./scripts/linux/travis.sh
environment:
  matrix:
    - NIM_GC: refc
      NIM_TAG_SELECTOR: version
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 4.8
    - NIM_GC: arc
      NIM_TAG_SELECTOR: version
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 4.8
    - NIM_GC: orc
      NIM_TAG_SELECTOR: version
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 4.8
    - NIM_GC: refc
      NIM_TAG_SELECTOR: '#head'
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 4.8
    - NIM_GC: arc
      NIM_TAG_SELECTOR: '#head'
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 4.8
    - NIM_GC: orc
      NIM_TAG_SELECTOR: '#head'
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 4.8
    - NIM_GC: refc
      NIM_TAG_SELECTOR: version
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 11
    - NIM_GC: arc
      NIM_TAG_SELECTOR: version
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 11
    - NIM_GC: orc
      NIM_TAG_SELECTOR: version
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 11
    - NIM_GC: refc
      NIM_TAG_SELECTOR: '#head'
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 11
    - NIM_GC: arc
      NIM_TAG_SELECTOR: '#head'
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 11
    - NIM_GC: orc
      NIM_TAG_SELECTOR: '#head'
      NIM_TARGET_CPU: amd64
      NIM_TARGET_OS: linux
      USE_GCC: 11
    - NIM_GC: refc
      NIM_TAG_SELECTOR: version
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 4.8
    - NIM_GC: arc
      NIM_TAG_SELECTOR: version
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 4.8
    - NIM_GC: orc
      NIM_TAG_SELECTOR: version
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 4.8
    - NIM_GC: refc
      NIM_TAG_SELECTOR: '#head'
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 4.8
    - NIM_GC: arc
      NIM_TAG_SELECTOR: '#head'
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 4.8
    - NIM_GC: orc
      NIM_TAG_SELECTOR: '#head'
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 4.8
    - NIM_GC: refc
      NIM_TAG_SELECTOR: version
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 11
    - NIM_GC: arc
      NIM_TAG_SELECTOR: version
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 11
    - NIM_GC: orc
      NIM_TAG_SELECTOR: version
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 11
    - NIM_GC: refc
      NIM_TAG_SELECTOR: '#head'
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 11
    - NIM_GC: arc
      NIM_TAG_SELECTOR: '#head'
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 11
    - NIM_GC: orc
      NIM_TAG_SELECTOR: '#head'
      NIM_TARGET_CPU: i386
      NIM_TARGET_OS: linux
      USE_GCC: 11
image: linux
version: 1.0.{build}
